### ISSUE TITLE
readme-python.txt is missing

### ISSUE THREAD

**Issue by frankgerhardt** [flok99/clewarecontrol#1]
The readme.txt refers to readme-python.txt. 

I'm looking for it because I could not get the Python example to work.

**Comment by flok99** [comment]
I've added and uploaded them now.
Thanks for reporting.

On Wed, Sep 23, 2015 at 7:25 PM, frankgerhardt <notifications@github.com>
wrote:

> The readme.txt refers to readme-python.txt.
>
> I'm looking for it because I could not get the Python example to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/clewarecontrol/issues/1>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by frankgerhardt** [comment]
Thank you
