### ISSUE TITLE
Let cleware run as non-root

### ISSUE THREAD

**Issue by frankgerhardt** [flok99/clewarecontrol#2]
The git clone and make install was easy. Thank you!

It works with sudo perfectly. What would have to to be changed so that it runs also as regular user?

**Comment by flok99** [comment]
You would need to create udev-rules.

From the top of my head (not tested);
add the following to /etc/udev/rules.d/10-local.rules
ATTRS{idVendor}=="0d50", MODE="0660", GROUP="cleware"

then add that group:

groupadd cleware
usermod -G cleware -a *your_login*

then reboot

please let me know if this works. if it works then I'll add it to the readme

On Wed, Sep 23, 2015 at 7:27 PM, frankgerhardt <notifications@github.com>
wrote:

> The git clone and make install was easy. Thank you!
>
> It works with sudo perfectly. What would have to to be changed so that it
> runs also as regular user?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/clewarecontrol/issues/2>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by frankgerhardt** [comment]
It works, thank you!

The output is a bit verbose. 
```
~$ clewarecontrol -as 0 0 
You did not select a device, using first device found.
Using device with serial number: 123456
Switch 0: set to Off
Switch 0: set to Off
Switch 0: set to Off
Switch 0: set to Off
Switch 0: set to Off
Switch 0: set to Off
Switch 0: set to Off
Switch 0: set to Off
Switch 0: set to Off
Switch 0: set to Off
~$ 
```

Is it possible to limit the output to 1-2 lines?

**Comment by flok99** [comment]
-c 1

On Fri, Sep 25, 2015 at 12:56 AM, frankgerhardt <notifications@github.com>
wrote:

> It works, thank you!
>
> The output is a bit verbose.
>
> ~$ clewarecontrol -as 0 0
> You did not select a device, using first device found.
> Using device with serial number: 123456
> Switch 0: set to Off
> Switch 0: set to Off
> Switch 0: set to Off
> Switch 0: set to Off
> Switch 0: set to Off
> Switch 0: set to Off
> Switch 0: set to Off
> Switch 0: set to Off
> Switch 0: set to Off
> Switch 0: set to Off
> ~$
>
> Is it possible to limit the output to 1-2 lines?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/clewarecontrol/issues/2#issuecomment-143071308>
> .
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by branens** [comment]
works thanks

/etc/udev/rules.d/10-local.rules
ATTRS{idVendor}=="0d50", MODE="0660", GROUP="cleware"

groupadd cleware
usermod -G cleware -a $USER
