### ISSUE TITLE
Be able to address more than one device from the same system

### ISSUE THREAD

**Issue by brother** [flok99/clewarecontrol#4]
I might miss something obvious somewhere, please help me forward then (or let's try to make the docs better).

I have two USB-ampel. And cleware -l lists them both as Device 0 and Device 1. Good and jolly. What I do not seem to graps is the possibility to address Device 1 in this chain. The identify as the same serial number (but have different serial numbers printed at the back...)

I am generally doing the following to communicate what color and state for that (on/off). 
´´´clewarecontrol -d "$serial" -F -as "$color" "$action"´´´

My first thought was to address them as different serials but they are not shown as different in clewarecontrol -l.

´´´
root /home/brother/git/other/traffic (master *%)# clewarecontrol -l
Cleware library version: 330
Number of Cleware devices found: 2
Device: 0, type: Switch1 (8), version: 102, serial number: 901377
Device: 1, type: Switch1 (8), version: 102, serial number: 901377
´´´

What am I missing?

**Comment by flok99** [comment]
This is a bug.

You are using the git version right?
Can you check if
http://www.vanheusden.com/clewarecontrol/clewarecontrol-2.8.tgz also gives
this same serial number?

On Wed, Oct 7, 2015 at 12:46 PM, brother <notifications@github.com> wrote:

> I might miss something obvious somewhere, please help me forward then (or
> let's try to make the docs better).
>
> I have two USB-ampel. And cleware -l lists them both as Device 0 and
> Device 1. Good and jolly. What I do not seem to graps is the possibility to
> address Device 1 in this chain. The identify as the same serial number (but
> have different serial numbers printed at the back...)
>
> I am generally doing the following to communicate what color and state for
> that (on/off).
> ´´´clewarecontrol -d "$serial" -F -as "$color" "$action"´´´
>
> My first thought was to address them as different serials but they are not
> shown as different in clewarecontrol -l.
>
> ´´´
> root /home/brother/git/other/traffic (master *%)# clewarecontrol -l
> Cleware library version: 330
> Number of Cleware devices found: 2
> Device: 0, type: Switch1 (8), version: 102, serial number: 901377
> Device: 1, type: Switch1 (8), version: 102, serial number: 901377
> ´´´
>
> What am I missing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/clewarecontrol/issues/4>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by brother** [comment]
I am not sure what version I am using. Bad of me. I'll try that and report back.

update:
root /home/brother# clewarecontrol -l
Cleware library version: 330
Number of Cleware devices found: 1
Device: 0, type: Switch1 (8), version: 102, serial number: 901377


probably an old binary indeed.

**Comment by brother** [comment]
RIght. git HEAD seems to not work very well. I do not think that I used that version before though. Probably an older tar ball. The linked clewarecontrol-2.8.tgz builds clean and shows different serial IDs. 

And yes indeed I can address them both good. Thnx.
